image: gitlab_runner_images:12.13.0-alpine
cache:
  key: QCD_CLIENT_NODE_MODULE
  paths:
    - node_modules/

stages:
  - build

build-it:
  stage: build
  before_script:
    - rm -rf ~/.ssh || true
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - yarn install
    - yarn build-it
    - scp -i ~/.ssh/id_rsa -o 'StrictHostKeyChecking no' -r dist arrow@192.168.1.4:/home/arrow/projects/jira_qcd_test/jira_qcd_client/
  artifacts:
    paths:
      - dist
  only:
    - develop

build-prod:
  stage: build
  before_script:
    - rm -rf ~/.ssh || true
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - yarn install
    - yarn build-prod
    - scp -i ~/.ssh/id_rsa -o 'StrictHostKeyChecking no' -r dist arrow@192.168.1.4:/home/arrow/projects/jira_qcd/jira_qcd_client/
  artifacts:
    paths:
      - dist
  only:
    - master
